// const
// const
// const
// const
// const
export const agreementText =
  ' By visiting or using this website, you acknowledge and agree to adhere to the terms outlined herein and pledge not to engage in any unlawful activities that may adversely affect Naxtro Trade Plus, its directors, officers, subsidiaries, affiliates, or business partners, collectively referred to as the "Released Parties". Naxtro Trade Plus reserves the right to amend or update these terms at any time with prior notification. Your continued use of this website following any such changes signifies your acceptance of the modified terms. These terms, along with any referenced documents, constitute the entire agreement between Naxtro Trade Plus and yourself regarding the subject matter herein and supersede all prior communications, whether electronic, oral, or written. By accessing and utilizing this website, you (and your parent/legal guardian if you are under the age of majority in your jurisdiction) affirm that you have read, comprehended, and consented to be legally bound by these terms, and agree to comply with all applicable laws and regulations, which may be revised periodically. If you do not accept or agree to be legally bound by these terms, you are prohibited from accessing or using the website.';

export const copyRightText =
"This website, including its logos, texts, graphics, trademarks, and images, is owned by Naxtro Trade Plus or used under license. All content is protected by intellectual property laws, including those of the United Kingdom. Reproduction, distribution, or modification of any content without prior written consent from Naxtro Trade Plus is prohibited. Limited permission is granted for personal, non-commercial use, provided copyright and trademark notices are displayed. By accessing this website, you agree to comply with these terms and applicable laws."
export const trademarksText =
 
"The Naxtro Trade Plus trademark and related figurative trademarks displayed on this website are registered trademarks and the exclusive property of Naxtro Trade Plus, its subsidiaries, affiliates, members, suppliers, or distributors. They are protected under worldwide trademark legislation and regulations, including those of the United Kingdom. Any trademarks and figurative trademarks not owned by Naxtro Trade Plus are the property of their respective owners."
export const hyperlinksText =

"We encourage you to explore the hyperlinks on this website, which provide access to various pages within this site or to third-party websites. Hyperlinks to third-party websites are provided for informational purposes only. Naxtro Trade Plus does not control these websites and bears no responsibility for their content. The Released Parties absolve themselves of any liability related to the content, representations, or information found on third-party websites accessible via hyperlinks. These websites may have their own privacy policies and terms and conditions that differ from those outlined in these Terms. Naxtro Trade Plus is not accountable for the privacy practices or content of any websites owned and operated by subsidiaries, affiliates, or third parties. Therefore, we recommend carefully reviewing the privacy policy and terms and conditions of each third-party website you visit. Unless explicitly stated otherwise, the presence of hyperlinks on this website to third-party websites should not be construed as an endorsement by Naxtro Trade Plus of the content or representations found on those websites, nor as a indication of partnership or affiliation with their owners."
export const correctionText =
 
"The products and articles showcased on this website are those that may be available for sale in the United Kingdom by Naxtro Trade Plus. Naxtro Trade Plus endeavors to offer accurate descriptions of these products or articles. However, Naxtro Trade Plus does not guarantee the accuracy, completeness, or reliability of these descriptions, including any information regarding product or article prices."
export const governingText =
  "These Terms and Conditions are governed by the laws of the applicable laws of United Kingdom and these laws apply to the use of this Website or the information contained on this Website by you, notwithstanding your domicile, residency or physical location. This Website or the information contained on this Website are intended for use only in jurisdictions where it may lawfully be offered for use.";
export const privacyText =
  "Without limiting the generality of these Terms, your use of the Website is also subject to the terms of our Privacy Policy, which is hereby incorporated into and made part of these Terms. Please carefully review our Privacy Policy. By using the Website, you (and your parent or legal guardian on your behalf, if you are under the age of majority in your jurisdiction of residence) signify that you have read, fully understand and agree to be legally bound by our Privacy Policy.";
export const multipleText =
  "A member with multiple accounts to gain a referral bonus or for any other reason shall be suspended without pay.";
export const generalText =
  "If any provision of these Terms is held invalid or unenforceable by any court having competent jurisdiction, such provision shall be enforced to the maximum extent permitted by law, and the remaining provisions of these Terms shall continue in full force and effect. No failure to exercise or waiver of any provision of these Terms shall be deemed a further or continuing waiver of such provision or any other provision of these Terms.";
